### PR TITLE
Added Quick Sort Algorithm in C++

### PR DESCRIPTION
**Pull request by DeveloperPaul123**
See #16

### CODE REVIEW

**Comment by sauravjaiswalsj** [comment]
Your branch has some conflicts.Please resolve it.

**Comment by DeveloperPaul123** [comment]
May I ask why this was closed? You only commented on the branch conflicts an hour ago? 
image

**Comment by sauravjaiswalsj** [comment]
The issue has already been solved.

**Comment by sauravjaiswalsj** [comment]
I have reopend your pr you can resolve your conflicts.

**Comment by DeveloperPaul123** [comment]
Great thanks. Done!

**Pull request merged**
